// NOTICE: DO NOT EDIT THIS FILE
// There are no issues in this File.

import { students } from "./students.js";
import { calculateSemesterGrade } from "./calculateSemesterGrade.js";

function printSemesterGrades(students) {
  const semesterGradeTable = students.map((student) => ({
    name: student.name,
    semesterGrade: calculateSemesterGrade(student),
  }));

  console.table(semesterGradeTable);
}

printSemesterGrades(students);
